### ISSUE TITLE
中文适配问题，以及其他的一些小问题

### ISSUE THREAD

**Issue by dscmarkw** [linsyking/CanvasHelper2#4]
1.电脑默认使用GBK编码的情况下，课程名和Title使用中文会变成乱码，但是作业内容里的中文又是正常的。如果将电脑默认编码改成UTF-8则直接在运行"uvicorn canvas_app:app --port 9283"时就报错。由于用的是非密院的Canvas，所以课程名也
恕本人水平有限并不知道问题出在哪，只能将自己使用时发现的问题放在这里。
2. 现在的Readme对用户有点不太友好，特别是把配置文件的方法也删掉了，如果以前也没用过初代canvashelper的话现在也并不知道该怎么操作。也许是2代刚开始开发的缘故吧。
3. 现在任务栏会有一个Terminal一直在那里，如果关掉窗口的话程序也会被关掉。不知道有没有什么可以隐藏掉这个Terminal的方法。
4. 配置课程的时候读取到了一堆以往学期的课程，但有很多本学期的课程没读到。不过这并不影响使用，毕竟可以手动添加。

**Comment by linsyking** [comment]
配置文件你能使用<https://canvashelper2.web.app/canvashelper/>吗？

**Comment by linsyking** [comment]
请把系统信息、python版本发一下谢谢

**Comment by linsyking** [comment]
本学期课程无法读到的问题我这里暂时没办法复现。能把<你的canvas地址>/api/v1/courses的结果附上来吗?

**Comment by linsyking** [comment]
关于1,请把报的错也贴出来谢谢

**Comment by dscmarkw** [comment]
> 关于1,请把报的错也贴出来谢谢

Traceback (most recent call last):
  File "E:\conda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\conda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\conda\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
  File "E:\conda\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "E:\conda\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "E:\conda\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\conda\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "E:\conda\lib\site-packages\uvicorn\main.py", line 404, in main
    run(
  File "E:\conda\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "E:\conda\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "E:\conda\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\conda\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "E:\conda\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "E:\conda\lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "E:\conda\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "E:\conda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\code\github\CanvasHelper2\.\canvas_app.py", line 40, in <module>
    conf = ConfigMGR()
  File "E:\code\github\CanvasHelper2\.\config_mgr.py", line 34, in __init__
    self.force_read()
  File "E:\code\github\CanvasHelper2\.\config_mgr.py", line 58, in force_read
    self.configuration = json.load(f)
  File "E:\conda\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "E:\conda\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 490: invalid start byte
以上报错只有在把Windows语言设置里的UTF-8选项打开时出现，只要关掉就不报错但是乱码。
python版本3.9.13/conda 22.9，系统Win11 22H2

api里读到的课程和https://yydbxx.cn/canvashelper/读到的一样，都是读了一堆以往学期的课但是缺本学期的，就不贴了。

**Comment by linsyking** [comment]
4已经修复

**Comment by linsyking** [comment]
使用[配置网站](https://canvashelper2.web.app/canvashelper)可以测试，但是需要更新客户端

**Comment by linsyking** [comment]
wallpaper engine上的壁纸已更新

**Comment by linsyking** [comment]
1也已经修复

**Comment by linsyking** [comment]
关于2

预计在配置网站增加如下解释
- 如何获取access token
- 如何手动修改配置文件及背景图片位置等

**Comment by linsyking** [comment]
3的方法已经提供在Readme中
